# Generated by Django 5.0.6 on 2024-05-25 14:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
