# Generated by Django 5.0.6 on 2024-05-25 16:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_projects_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
